### ISSUE TITLE
Numbers with international comma as decimal issue

### ISSUE THREAD

**Issue by tlauterbach** [FilamentGames/BeauData#2]
https://github.com/BeauPrime/BeauData/blob/19df3a3582005a115db2a387da78b593b5eebcca/Assets/BeauData/JSON.cs#L1078

This is the line in particular that most likely needs to be changed to force using a `.` instead of whatever the user's localized decimal symbol is

**Comment by BeauPrime** [comment]
Fixed with commit 54e977250d5d7ed59fcf21d1d0e526220e106d11 and merged into master
